# CircleCI pipeline processing engine, see https://circleci.com/docs/2.0/configuration-reference/
version: 2.1

jobs:
  ctrz:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Install aws-cli
          command: |
            pip install --user awscli==1.16.156
      - run:
          name: Make awscli available
          command: |
            echo 'export PATH=$HOME/.local/bin:$PATH' >> $BASH_ENV
      - run:
          name: Build and publish image
          command: |
            ./containerize.sh -p

workflows:
  build_docker_image:
    jobs:
    - ctrz:
        context: ecr-2738
        filters:
          tags:
            only: /.*/
